repos:
- repo: local
  hooks:
  - id: dart-format
    name: Dart Format
    entry: dart format
    language: system
    types: [ dart ]
    pass_filenames: true
  - id: flutter-analyze
    name: Flutter Analyze
    entry: flutter analyze
    language: system
    types: [ dart ]
    pass_filenames: false
  - id: shellcheck
    name: ShellCheck
    entry: shellcheck
    language: system
    types: [ shell ]
    pass_filenames: true
