repos:
- repo: local
  hooks:
  - id: flutter-format
    name: Flutter Format
    entry: flutter format
    language: system
    types: [ dart ]
    pass_filenames: true
  - id: flutter-analyze
    name: Flutter Analyze
    entry: flutter analyze
    language: system
    types: [ dart ]
    pass_filenames: false
